name: responsive_admin_dashboard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_route: ^6.3.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^6.2.0


flutter:
  uses-material-design: true
